use_frameworks!

platform :ios, '9.0'

target 'HQJNetwork_Example' do
  pod 'HQJNetwork', :path => '../'

  target 'HQJNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
